spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017
            database: bridge
mercadopago:
 client_id: 6637026896686804
 client_secret: gEMjH1wt7q5ToESeRWlDPOiykrf23aKB
 back_url: localhost:8080
 
 
 #{"id":257953849,"nickname":"TETE5813279","password":"qatest1533","site_status":"active","email":"test_user_2634434@testuser.com"}
 #{"id":257956135,"nickname":"TETE5610508","password":"qatest1966","site_status":"active","email":"test_user_81310653@testuser.com"