spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017
            database: bridge
mercadopago:
 client_id: 6637026896686804
 client_secret: gEMjH1wt7q5ToESeRWlDPOiykrf23aKB
 back_url: http://localhost:8080/v1/api/payment/MPResponse
 
 
